apiVersion: v1
kind: Service
metadata:
  name: hello-world-python-svc
  labels:
    app: hello-world-python-dev
    environment: dev
spec:
  type: LoadBalancer
  selector:
    app: hello-world-python-dev
  ports:
  - name: http
    protocol: TCP
    port: 80
    targetPort: 5000
