apiVersion: v1
kind: Service
metadata:
  name: hello-world-python-service
spec:
  type: LoadBalancer
  selector:
    app: hello-world-python
  ports:
    - protocol: TCP
      port: 80
      targetPort: 5000
