apiVersion: v1
kind: Service
metadata:
  name: hello-world-python-service-dev
  labels:
    app: hello-world-python
    environment: dev
spec:
  type: LoadBalancer
  selector:
    app: hello-world-python
    environment: dev
  ports:
  - protocol: TCP
    port: 80
    targetPort: 5000